# 基础配置（保留你原有的设置）
title: My Blog
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/666" # 必须设置为仓库名，否则链接会失效
url: "https://twilightsnow2009.github.io" # 部署后的完整URL（不带仓库名）
twitter_username: your-twitter-handle
github_username:  your-github-handle

# 新增Jekyll核心配置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/ # 文章永久链接格式
timezone: Asia/Shanghai # 设置时区（根据你的位置调整）

# 文章与页面配置
paginate: 5 # 每页显示5篇文章
paginate_path: "/page:num/" # 分页路径
show_drafts: false # 不显示草稿文章
future: false # 不显示日期在未来的文章

# 集合与默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # 默认为文章启用评论

# 插件配置（补全插件列表）
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
